name: rbig
channels:
- defaults
- conda-forge
dependencies:
- scipy
- scikit-learn
- numpy
- matplotlib
- numexpr
- cython
- pip
- pip:
    - python-picard
    - git+https://github.com/statsmodels/statsmodels