name: rbig_dev
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- numpy
- scipy
- scikit-learn
# Plotting Packages
- matplotlib
- seaborn
# GUI
- conda-forge::nodejs               # for extensions in jupyterlab
- conda-forge::tqdm       
# Pip Packages
- pip
- pip:
    - statsmodels
    - python-picard
    # GPY
    - "git+https://github.com/SheffieldML/GPy.git#egg=GPy"
    # Jupyter
    - ipykernel
    - ipywidgets
    # Formatters
    - black                   # no nonsense formatter
    - pylint                  # linter
    - isort                   # imports sorter
    - flake8                  # linter
    - mypy                    # type checker
    - pytest                  # testing suite
    - pyprojroot   # resolves paths in notebooks
    # Extra
    - netCDF4
    # Documentation
    - mkdocs-material 
    - mknotebooks
    - pymdown-extensions 
    - pdoc3