name: rbig
channels:
- defaults
- conda-forge
dependencies:
- python=3.9
# Standard Libraries
- numpy            # Numerical Linear Algebra
- scipy             # Scientific Computing
- scikit-learn     # Machine Learning
- conda-forge::statsmodels
# Plotting Libraries
- matplotlib        # standard plotting library
- seaborn          # Stats viz library
# GUI
- conda-forge::ipywidgets
- ipykernel
- conda-forge::tqdm
- pip
- pip:
    - einops
    - corner
    # Server/Logging
    - wandb
    # Formatters
    - black
    - pylint
    - isort
    - flake8
    - mypy
    - pytest
    # JupyterLab recognition
    - pyprojroot
